
name: Salary MLOps Pipeline

on: 
    push:                                              #what code to write will written in the push
        branches:                                     #used for telling us about the main branch
            -Cat (main)

Name: Salary MLOps Pipeline

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
 
      - name: Install Dependencies
        run: |                                             # | this single bar line is used for running .yaml codes
          pip install -r requirements.txt

      - name: Install Pytest
        run: |
            pip install pytest

      - name: Run API Tests
        run: |
            pytest tests/

      - name: Verify Imports
        run: |
          python -c "import fastapi"                        # this can be used to train the model in the pipeline
          python -c "import mlflow"
          python -c "import sklearn"
 
      - name: Workflow Completed
        run: echo "CI Pipeline Successful!"
